### ISSUE TITLE
Segmentation fault on Pick primitive

### ISSUE THREAD

**Issue by anthonyquizon** [dzaima/CBQN#107]
Hello,
I received a segmentation fault when trying to parse an csv file
Here is an example of my code
```
l ← •file.Lines "./data.csv"
m←l=',' ⋄ p ← ((¬m)/¨l)⊔˜¨(¬m)/¨+`¨m ⋄ h ← ⥊>1↑p ⋄ t ← >1↓p
z ← 0≠≠¨˘t
•Show 3⊸⊑˘z
```

with output
```
[1]    31977 segmentation fault  bqn main.bqn
```

I've added an example csv file here:
https://gist.github.com/anthonyquizon/8954108913b6dda3a3e6498b8822aadf

My bqn interpreter is compiled with the debug flag 'ie. make debug' using the latest code in the master branch.

Here is the where lldb stops
<img width="1047" alt="Screenshot 2024-02-27 at 4 05 31 pm" src="https://github.com/dzaima/CBQN/assets/1674432/1a2c33ea-d1c0-4ad8-80e9-641fc2cfe11d">

Here is my `bqn --version` output
```
CBQN on commit 8c18fddd5483c5fba658f24674b004e4444bf72d
built with FFI, singeli aarch64, replxx, optimizations disabled, debugging checks enabled (DEBUG)
```

I'm running on an iMac with M3 chip using Sonoma 14.1.1

If I remove ` h ← ⥊>1↑p ` from the above code I get this error message:
```
Bad used range for 0x101079680: 8..144, allocation size 128, usable 64
```

I initially tried on the version in nix with is 0.4.0 and got a similar issue.

**Comment by dzaima** [comment]
Thanks for the report! Simpler case: `⊑˘5000‿2⥊0`

`⊑˘` was using an allocation size calculation not meant for a packed bit boolean array input, and thus was always requesting 0 bytes of memory, resulting in various amounts of memory corruption.

Fix is on `develop` branch [here](https://github.com/dzaima/CBQN/commit/0c3d83c50b9f895b8820b56db7ddeb1d86795680)

**Comment by anthonyquizon** [comment]
> Thanks for the report! 

Thanks for CBQN!
