### ISSUE TITLE
Segmentation fault in `select_ucw()` built with gcc (Debian 14.2.0-8)

### ISSUE THREAD

**Issue by llasram** [dzaima/CBQN#128]
```
$ git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.

$ git rev-parse --short HEAD
81abc808

$ make o3g CC=gcc
0/0 in 0.1s

$ ./BQN -e '1⌾(⟨0⟩⊸⊏)⟨0⟩'
Segmentation fault

$ gcc --version | head -n1
gcc (Debian 14.2.0-8) 14.2.0
```

And obviously works fine with `clang`.

A tiny bit of poking suggests the condition at [src/builtins/select.c:947](https://github.com/dzaima/CBQN/blob/81abc808635e963204557ac4af60eb71bf0148eb/src/builtins/select.c#L947) is getting optimized to be always true, but that's as far as I got.  Hopefully reproduces with a version of `gcc` you have handy!

**Comment by dzaima** [comment]
Fixed in 5ecd1858eff497ab8ebd8114860f9a2bb0d39d93; `RNK(rep)` was being ran before the check whether `rep` is an array.
