### ISSUE TITLE
error: static declaration of 'gc_visitRoots' follows non-static declaration

### ISSUE THREAD

**Issue by thezjy** [dzaima/CBQN#13]
got this error after running `make o3` on Ubuntu 20.04 LTS:

> 
> In file included from src/core/../opt/mm_buddy.c:1,
>                  from src/core/mm.c:6:
> src/core/../opt/gc.c:54:13: error: static declaration of 'gc_visitRoots' follows non-static declaration
>    54 | static void gc_visitRoots() {
>       |             ^~~~~~~~~~~~~
> In file included from src/core/../core.h:2,
>                  from src/core/mm.c:1:
> src/core/../h.h:275:6: note: previous declaration of 'gc_visitRoots' was here
>   275 | void gc_visitRoots(void);
>       |      ^~~~~~~~~~~~~

remove the `static` on line 54 then it works.

**Comment by dzaima** [comment]
pushed that change. Slipped in during a small refactoring, and for whatever reason it doesn't error on my setup.
