### ISSUE TITLE
OSX build meet error.

### ISSUE THREAD

**Issue by secwang** [dzaima/CBQN#26]
ld: unknown option: --dynamic-list=include/syms
clang: error: linker command failed with exit code 1 (use -v to see invocation)

when make ffi=0 , it's ok

**Comment by dzaima** [comment]
To build with FFI you can also `make LD_LIBS='-ldl -lffi'` (potentially with `C_INCLUDE_PATH=/usr/local/opt/libffi/include:$C_INCLUDE_PATH LIBRARY_PATH=/usr/local/opt/libffi/lib:$LIBRARY_PATH` beforehand if libffi isn't in the library paths already). Just haven't gotten around to detecting OS & deciding what options to add based on that.

**Comment by secwang** [comment]
yes `make LD_LIBS='-ldl -lffi'` solve it.
thank you
