### ISSUE TITLE
Building without precompiled bytecode

### ISSUE THREAD

**Issue by yewscion** [dzaima/CBQN#27]
Is there a way to build CBQN without relying on the precompiled bytecode in the bytecode branch?

I would like to package BQN for GNU Guix, but to do it must be built without any precompiled binaries.

**Comment by yewscion** [comment]
I guess what I'm really asking for is a commit that can be built as an intermediate step, so I can package that and use it to build the contemporary CBQN versions.

**Comment by dzaima** [comment]
CBQN itself can't bootstrap itself, and never could; you'd need to use [dzaima/BQN](https://github.com/dzaima/BQN), which is a separate BQN implementation completely written in Java (and so doesn't need bootstrapping itself), with which, (after building it with `./build` in its directory), you can do `java -jar path/to/dzaima/BQN/BQN.jar path/to/CBQN/genRuntime path/to/mlochbaum/BQN` to generate the bytecode.

**Comment by dzaima** [comment]
(yes, that's quite messy; at some point I would like to write a subset of a BQN compiler in C large enough that it could be used for bootstrapping (would also likely require a more complete native runtime), but that has very low priority to the point that it might just never happen)

**Comment by yewscion** [comment]
Thank You for the quick response! I was able to get the package written, and it seems to be working as intended now. I'll be creating a request to add the package to GNU Guix proper as soon as I learn enough BQN to make sure it works!

If You are interested in seeing the packages I've written, they live in [here](https://git.sr.ht/~yewscion/yewscion-guix-channel/tree/trunk/item/cdr255/bqn.scm) in my personal guix channel for now. I'm excited to get to learning!

Thanks again for Your help!
