### ISSUE TITLE
Error: Couldn't read file "./test/this.bqn"

### ISSUE THREAD

**Issue by yewscion** [dzaima/CBQN#28]
The above is the output for all of the *.sh-based tests echoes the above `Error: Couldn't read file "./test/this.bqn"`. Is this file supposed to exist at this point, or is another file meant to be tested?

**Comment by dzaima** [comment]
The `test/mainCfgs.sh`, `test/x86Cfgs.sh`, and `test/moreCfgs.sh` files require an argument of a path to [mlochbaum/BQN](https://github.com/mlochbaum/BQN), which is [where](https://github.com/mlochbaum/BQN/blob/master/test/this.bqn) the `test/this.bqn` file is.

**Comment by yewscion** [comment]
Ahhhh, okay. Sorry for the mistake; I thought the path needed was to the built BQN binary.
