### ISSUE TITLE
Release Tagging Question

### ISSUE THREAD

**Issue by yewscion** [dzaima/CBQN#47]
Right now we are packaging arbitrary commits of CBQN, for the packages that exist. However, it would be a better user experience if there were released versions that were guaranteed to work in a specific way, rather than simply installing a package of 'the latest commit'. 

Is there any way we could establish a release tag (and therefore a development version) for CBQN, so that the packaged versions can be sure to coincide with specific updates and features?

**Comment by dzaima** [comment]
Versioning has been discussed multiple times before in the BQN chatroom. With the current rapid pace of optimization work, having stable versions would require backporting of bugfixes, which is time I'd rather put into working on more actual features & optimizations. And, without backporting, the latest commit should just be the most stable one, in addition to having all new features (though new features is kind of rare currently).

A version on each commit or new day has been suggested, but I don't see too much value in that over just the git commit (other than numeric versions being easier to compare, but if versions aren't tied to any features or stability/support or timeframe, there's not much reason for any comparison other than "am I on the latest commit").

(of course, versioning will need to happen at some point; I just don't think that's quite yet.)

**Comment by dzaima** [comment]
v0.1.0 exists now as a git tag.
