### ISSUE TITLE
Compilation failed with last version

### ISSUE THREAD

**Issue by srw** [dzaima/CBQN#50]
make

builtins/arithm.c
builtins/arithd.c
builtins/cmp.c
builtins/sfns.c
builtins/squeeze.c
builtins/select.c
builtins/slash.c
builtins/group.c
builtins/sort.c
builtins/selfsearch.c
builtins/md1.c
builtins/md2.c
builtins/fns.c
builtins/sysfn.c
builtins/internal.c
builtins/inverse.c
core/tyarr.c
core/harr.c
core/fillarr.c
core/stuff.c
core/derv.c
core/mm.c
core/heap.c
Copying precompiled bytecode from the bytecode branch
**git checkout remotes/origin/bytecode src/gen/{compiles,formatter,runtime0,runtime1,src,explain}
fatal: not a git repository (or any of the parent directories): .git**
make[2]: *** [makefile:224: src/gen/customRuntime] Error 128
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [makefile:176: run_incremental_0] Error 2
make: *** [makefile:7: o3] Error 2

**Comment by dzaima** [comment]
You likely downloaded the source without using git. To be able to build CBQN, you need to `git clone` it, as CBQN uses other branches & git submodules for certain things.

**Comment by srw** [comment]
That works, thank you very much.
