### ISSUE TITLE
How to write special characters at the console (and define de prompt)

### ISSUE THREAD

**Issue by srw** [dzaima/CBQN#51]
I compiled and executed CBQN, now when I run it it shows an empty prompt and I don't see how to type special characters with a normal US keyboard:

```
user@machine:~/path/path/CBQN$ ./BQN 
   "hello"
"hello"
```

**Comment by dzaima** [comment]
CBQN doesn't include any keyboard setup. See https://mlochbaum.github.io/BQN/editors/index.html for ways to type BQN glyphs.

**Comment by dzaima** [comment]
(you'll want to use `rlwrap` to have expression history & be able to edit the line with arrow keys & whatnot. The prompt just is three spaces.)

**Comment by srw** [comment]
So, if I use a plain terminal how could I type a special character? Is that possible? Could you please give me an example? Thanks!

**Comment by dzaima** [comment]
One way would be to save [the inputrc file](https://github.com/mlochbaum/BQN/blob/master/editors/inputrc) somewhere on your system, and run `INPUTRC=/path/to/that/inputrc rlwrap ./BQN`; that'll give you the backslash entry method as per [this](https://mlochbaum.github.io/BQN/keymap.html) layout.
