### ISSUE TITLE
What would need to be done to allow http request from BQN?

### ISSUE THREAD

**Issue by tyoc213** [dzaima/CBQN#65]
I have tried to find examples on how to do `get`, `post` and so on request with and without cookies or json and so on....

Is there a way to support it? maybe using FFI???

**Comment by dzaima** [comment]
I've heard of people using `curl` through `•SH`, which is probably easier than FFI. But there's nothing native for it (at least currently, but it'll probably stay this way for a while) as it's quite a large undertaking, with an immense amount of potentially configurable things.
