### ISSUE TITLE
[BUG] Typing in REPL Spacing Issue with `𝕨` and `𝕩`

### ISSUE THREAD

**Issue by codereport** [dzaima/CBQN#68]
I `git clone`d and then ran `make CC=cc REPLXX=1` to build it. Issue is when I am typing, it double inputs a space sometimes and then the cursor is off. It seems to be related to the double struck characters `𝕨` and `𝕩`.

![2023-03-02 12-15-51](https://user-images.githubusercontent.com/36027403/222503539-2ae96797-2535-438c-82db-98fe674eb4ae.gif)

**Comment by dzaima** [comment]
What terminal are you using? Does `𝕨`/`𝕩`  work properly if typed in the bash session and not CBQN?

**Comment by codereport** [comment]
I am using WSL2 on Windows 11. And yea, it does look like outside of CBQN it is also messed up. That sucks ...

**Comment by dzaima** [comment]
Yeah, quite a few terminals on Windows don't handle the double-struck characters properly, as Windows is UTF-16-centric, where those are surrogate pairs, which I guess noone bothers testing; [this](https://mlochbaum.github.io/BQN/#how-do-i-work-with-the-character-set) mentions that `wsl-terminal`, or the terminal within VS Code, are options that will properly handle them, but this isn't something that could be fixed within CBQN.
