### ISSUE TITLE
undefined reference to `_pdep_u64'

### ISSUE THREAD

**Issue by taigua** [dzaima/CBQN#72]
Compile failed using `make o3n`
[CPU]: Intel(R) Core(TM) i7-10700F
[OS]: WSL2 (Ubuntu jammy)
[Kernel]: Linux version 5.15.90.1-microsoft-standard-WSL2
[CC]: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 / Ubuntu clang version 14.0.0-1ubuntu1
[Error]:
src/utils/bits.c:155:47: warning: implicit declaration of function '_pdep_u64' is invalid in C99 [-Wimplicit-function-declaration]
        for (ux i=0; i<am; i++) { *(u64*)rp = _pdep_u64(rbuu64(xp, i*count), msk0); rp++; }
                                              ^
src/utils/bits.c:160:23: warning: implicit declaration of function '_pdep_u64' is invalid in C99 [-Wimplicit-function-declaration]
          *(u64*)rp = _pdep_u64(rbuu64(xp, am*count), msk1);
                      ^
src/utils/bits.c:241:47: warning: implicit declaration of function '_pext_u64' is invalid in C99 [-Wimplicit-function-declaration]
        for (ux i=0; i<am; i++) { ab_add(&ab, _pext_u64(*(u64*)xp, msk0), count); xp+= 8; }
                                              ^
src/utils/bits.c:246:23: warning: implicit declaration of function '_pext_u64' is invalid in C99 [-Wimplicit-function-declaration]
          ab_add(&ab, _pext_u64(*(u64*)xp, msk1), POPC(msk1));
                      ^
4 warnings generated.
/usr/bin/ld: build/obj/def_o3n/bits.o: in function `zeroPadToCellBits0':
bits.c:(.text+0xdbc): undefined reference to `_pdep_u64'
/usr/bin/ld: bits.c:(.text+0xe18): undefined reference to `_pdep_u64'
/usr/bin/ld: build/obj/def_o3n/bits.o: in function `narrowWidenedBitArr':
bits.c:(.text+0x1938): undefined reference to `_pext_u64'
/usr/bin/ld: bits.c:(.text+0x1c44): undefined reference to `_pext_u64'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [makefile:255: build/obj/def_o3n/BQN] Error 1
make[1]: *** [makefile:225: run_incremental_0] Error 2
make: *** [makefile:11: o3n] Error 2

**Comment by dzaima** [comment]
Forwarded `master` a bit; this has been fixed in `develop` for a while.
