### ISSUE TITLE
Can't build shared library on Linux

### ISSUE THREAD

**Issue by iacore** [dzaima/CBQN#75]
Don't know why. `make` works (producing `./BQN`).

```
2 ❯ make shared-o3

automatically-built bootstrap CBQN doesn't behave as expected; run 'make for-build' with necessary configuration manually
make[1]: *** [makefile:50: to-bqn-build] Error 1
make: *** [makefile:85: shared-o3] Error 2

❯ ./BQN build/src/build.bqn
Error: Native compiler: Can't tokenize \u5f / 95
```

tried Option 2 of bootstraping. didn't work either

**Comment by dzaima** [comment]
yeah, known issue; run `make clean; make for-build`, then `make shared-o3` should work; or, alternatively, switch to the `develop` branch & run `make clean` (this is unrelated to the bootstrapping compiler; it can't be used for anything other than running `build/bootstrap.bqn`)

I'll make a fixed release sometime maybe tomorrow.

**Comment by iacore** [comment]
> make clean; make for-build, then make shared-o3 

This worked. Thanks!

**Comment by dzaima** [comment]
Made a 0.2.0 + updating `master` of that now.
