### ISSUE TITLE
[Consult/Question] BQN Kernel for Jupyter Notebook

### ISSUE THREAD

**Issue by vergelli** [dzaima/CBQN#77]
Hello again and sorry in advance if this is offtopic, or does not belong here.
I was wondering if there is any project that achieves running BQN cells on Notebooks.

**Comment by dzaima** [comment]
Don't recall anything about jupyter exactly, but there is http://bqnpad.mechanize.systems/notebook and https://observablehq.com/@lsh?tab=notebooks. General BQN questions are better off in [the chatroom](https://mlochbaum.github.io/BQN/community/forums.html) though.
