### ISSUE TITLE
Release tags do not include libraries

### ISSUE THREAD

**Issue by BryceVandegrift** [dzaima/CBQN#79]
The zip and tar.gz [files](https://github.com/dzaima/CBQN/tags) for CBQNs tags do not include cbqnBytecode, replxx, or Singeli.
Running `make` from these archives results in an error since these archives are not git repos and don't include these libraries:
```
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by dzaima** [comment]
Not much I can do about it, as those are autogenerated by github. I suppose I could upload custom ones too, but that'd take having github releases (whereas currently it's just a git tag; that's apparently all it takes for github to start autogenerating those broken archives), and they'd still have the autogenerated things anyway afaict. Cloning the project is still the way to install it.

**Comment by BryceVandegrift** [comment]
Ok, I just thought that this might be something that was overlooked.
