### ISSUE TITLE
font question

### ISSUE THREAD

**Issue by alexhraber** [dzaima/CBQN#94]
Do you have a recommended font for running this locally in urxvt? :pray:

**Comment by dzaima** [comment]
Various fonts are listed at https://mlochbaum.github.io/BQN/fonts.html. I personally have the "DejaVu Sans Mono BQN" there installed as a global font overriding the regular "DejaVu Sans Mono", so that dejavu used anywhere (incl. terminals) gets nice BQN symbols.
